version: "3.8"

services:
  db:
    image: postgres:14.2-alpine
    restart: always
    container_name: "dev-db"
    ports:
      - "${POSTGRES_HOST_PORT}:${POSTGRES_CONTAINER_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 5s
      retries: 3
    volumes:
      - ./db/:/docker-entrypoint-initdb.d/
  api:
    container_name: "dev-api"
    build:
      context: .
      dockerfile: api.dockerfile 
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_HOST_PORT}
    depends_on:
      db:
        condition: service_healthy
