version: '3'

tasks:
  all:
    cmds:
      - docker-compose build
      - docker-compose up
  build:
    cmds:
      - docker-compose build
  start:
    cmds:
      - docker-compose up
  stop:
    cmds:
      - docker-compose down
  clean:
    cmds:
      - docker system prune
  admin:
    cmds:
      - pnpm run -C admin dev