version: '3'

tasks:
  dev:
    cmds:
      - docker-compose up -d
      - yarn run dev --cwd /home/sean/Projects/splat/admin
    
  build:
    cmds:
      - docker-compose build
      - yarn run build --cwd /home/sean/Projects/splat/admin
  
  stop:
    cmds:
      - docker-compose down
