### LIST ROUTES ###
GET http://localhost:8080/api/v1/routes HTTP/1.1


### HEALTH CHECK ###
GET http://localhost:8080/api/v1/ping HTTP/1.1


### LIST POSTS ###
GET http://localhost:8080/api/v1/post HTTP/1.1
### GET POSTS ###
GET http://localhost:8080/api/v1/post HTTP/1.1

### CREATE POST ###
POST http://localhost:8080/api/v1/post HTTP/1.1
content-type: application/json
accept: application/json

{
  "title": "Third post",
  "content": "I'm going to make this list longersasdopasjdasjdasdaj"
}

### GET POST BY ID ###
GET http://localhost:8080/api/v1/post/09d9159b-c7fb-4be4-ae26-8ab3b83d8954 HTTP/1.1
content-type: application/json
accept: application/json


